# Generated by Django 3.1.2 on 2020-10-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='live_view',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='articles',
            name='source_code',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
